alias: "Мой Газ: Запросить счета за газ"
description: "Запросить счета за газ в сервисе Мой Газ"
trigger:
  - platform: time
    at: "01:00:00"
condition:
  - condition: template
    value_template: "{{ now().day == 5 }}"
action:
  - service: mygas.get_bill
    data:
      device_id: <YOUR_DEVICE_ID>
mode: single