alias: "Мой Газ: Запросить счета за газ на электронную почту"
description: "Запросить счета за газ на электронную почту в сервисе Мой Газ"
triggers:
  - at: "01:00:00"
    trigger: time
conditions:
  - condition: template
    value_template: "{{ now().day == 5 }}"
actions:
  - action: mygas.get_bill
    data:
      device_id: <YOUR_DEVICE_ID>
      email: <YOUR_EMAIL>
mode: single
