alias: "Мой Газ: Уведомление об ошибке при выполнения сервиса"
description: Уведомление об ошибке при выполнения сервиса Мой Газ
triggers:
  - event_type: mygas_send_readings_failed
    trigger: event
  - event_type: mygas_get_bill_failed
    trigger: event
  - event_type: mygas_refresh_failed
    trigger: event
conditions: []
actions:
  - data:
      config_entry_id: <YOUR_TELEGRAM_BOT_CONFIG_ENTRY_ID>  # Replace with your Telegram Bot config entry ID
      message: "{{ trigger.event.data.error }}"
      title: >-
        🔥Газ. {% if trigger.event.event_type == 'mygas_send_readings_failed' %}
        Ошибка при   передаче показаний для {% elif trigger.event.event_type
        ==   'mygas_get_bill_failed' %} Ошибка при получении счета для {% elif  
        trigger.event.event_type == 'mygas_refresh_failed' %} Ошибка при
        обновлении   информации для {% else %} Ошибка при выполнении сервиса для
        {% endif %}   {{device_attr(trigger.event.data.device_id,
        'name_by_user') or    device_attr(trigger.event.data.device_id, 'name')
        }} от {{   now().strftime('%d-%m-%Y %H:%M')}}
    action: telegram_bot.send_message
  - data:
      title: >-
        🔥Газ. {% if trigger.event.event_type == 'mygas_send_readings_failed' %}
        Ошибка при передаче показаний для {% elif trigger.event.event_type ==
        'mygas_get_bill_failed' %} Ошибка при получении счета для {% elif
        trigger.event.event_type == 'mygas_refresh_failed' %} Ошибка при
        обновлении информации для {% else %} Ошибка при выполнении сервиса для
        {% endif %} {{device_attr(trigger.event.data.device_id, 'name_by_user')
        or  device_attr(trigger.event.data.device_id, 'name') }}  от {{
        now().strftime('%d-%m-%Y %H:%M')}}
      message: "{{ trigger.event.data.error }}"
    action: notify.persistent_notification
mode: single
