alias: "Мой Газ: Уведомление об отправленных показаниях"
description: "Уведомление об отправленных показаниях в сервис Мой Газ"
triggers:
  - event_type: mygas_send_readings_completed
    trigger: event
conditions: []
actions:
  - data:
      config_entry_id: <YOUR_TELEGRAM_BOT_CONFIG_ENTRY_ID>  # Replace with your Telegram Bot config entry ID
      message: "Показания: {{ trigger.event.data.readings }}"
      title: >-
        🔥Газ. Показания для {{
        device_attr(trigger.event.data.device_id,'name_by_user') or  
        device_attr(trigger.event.data.device_id, 'name') }} отправлены {{  
        now().strftime('%d-%m-%Y %H:%M') }}
    action: telegram_bot.send_message
  - data:
      title: >-
        🔥Газ. Показания для {{
        device_attr(trigger.event.data.device_id,'name_by_user') or
        device_attr(trigger.event.data.device_id, 'name') }} отправлены {{
        now().strftime("%d-%m-%Y %H:%M") }}
      message: "Показания: {{ trigger.event.data.readings }}"
    action: notify.persistent_notification
mode: single
