alias: "Мой Газ: Отправить показания по газу"
description: "Отправить показания по газу в сервис Мой Газ"
triggers:
  - at: "02:00:00"
    trigger: time
conditions:
  - condition: template
    value_template: "{{ now().day == 24 }}"
actions:
  - alias: "Мой Газ: Отправить показания"
    action: mygas.send_readings
    data:
      value: <YOUR_READINGS_SENSOR>
      device_id: <YOUR_DEVICE_ID>
  - delay:
      minutes: 10
  - action: mygas.refresh
    data:
      device_id: <YOUR_DEVICE_ID>
mode: single
